try{
    let a= new Array(5);
   console.log(a[10])
}
 catch(err){
     console.log("Errrrrr"+err);
 }
 finally {
     console.log("default");
 }
 
 
 